version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  tls:
    certificate: /etc/registry/certs/registry.crt
    key: /etc/registry/certs/registry.key
